services:
  db:
    image: postgres:17-alpine
    container_name: cric_site_registry_db
    environment:
      POSTGRES_DB: site_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: cric_site_registry_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn site_registry.wsgi:application --bind 0.0.0.0:8000 --workers 3 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-fp#d%rf(+u90ude8++4uhpi+qfk26&t_m=yxpqpl@o4f!+1jg^"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/site_registry"
      POSTGRES_NAME: site_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
