apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cric-site-registry.fullname" . }}-config
  labels:
    {{- include "cric-site-registry.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.django.debug | quote }}
  ALLOWED_HOSTS: {{ .Values.django.allowedHosts | quote }}
  POSTGRES_NAME: {{ .Values.postgres.name | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_HOST: {{ include "cric-site-registry.postgresHost" . | quote }}
  POSTGRES_PORT: "5432"
