{{- if .Values.migrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cric-site-registry.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "cric-site-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "cric-site-registry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              python manage.py migrate --noinput &&
              python manage.py collectstatic --noinput
          envFrom:
            - configMapRef:
                name: {{ include "cric-site-registry.fullname" . }}-config
            - secretRef:
                name: {{ include "cric-site-registry.fullname" . }}-secret
{{- end }}
