{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cric-site-registry.fullname" . }}-postgres
  labels:
    {{- include "cric-site-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  podSelector:
    matchLabels:
      {{- include "cric-site-registry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "cric-site-registry.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: web
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
