apiVersion: v1
kind: Service
metadata:
  name: {{ include "cric-site-registry.postgresHost" . }}
  labels:
    {{- include "cric-site-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    {{- include "cric-site-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
