apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cric-site-registry.fullname" . }}-secret
  labels:
    {{- include "cric-site-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.django.secretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
