apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cric-site-registry.fullname" . }}-web
  labels:
    {{- include "cric-site-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cric-site-registry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "cric-site-registry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["gunicorn"]
          args:
            - "site_registry.wsgi:application"
            - "--bind=0.0.0.0:{{ .Values.web.port }}"
            - "--workers={{ .Values.web.workers }}"
          ports:
            - containerPort: {{ .Values.web.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "cric-site-registry.fullname" . }}-config
            - secretRef:
                name: {{ include "cric-site-registry.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            initialDelaySeconds: {{ add .Values.probes.initialDelaySeconds 10 }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
