# Generated by Django 6.0.3 on 2026-07-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Rucio RSE name, e.g. CERN-PROD_DATADISK",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("davs", "WebDAV/TLS"),
                            ("srm", "SRM"),
                            ("gsiftp", "GridFTP"),
                            ("xrootd", "XRootD"),
                            ("posix", "POSIX/local"),
                        ],
                        default="davs",
                        max_length=20,
                    ),
                ),
                (
                    "deterministic",
                    models.BooleanField(
                        default=True,
                        help_text="Whether LFN→PFN mapping is deterministic",
                    ),
                ),
                (
                    "free_tb",
                    models.FloatField(default=0.0, help_text="Free space in TB"),
                ),
                (
                    "used_tb",
                    models.FloatField(default=0.0, help_text="Used space in TB"),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Parent computing site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rses",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSE",
                "verbose_name_plural": "RSEs",
                "ordering": ["name"],
            },
        ),
    ]
