# Generated by Django 6.0.3 on 2026-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("region", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("degraded", "Degraded"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("cpu_capacity", models.IntegerField(help_text="Total CPU cores")),
                ("storage_tb", models.FloatField(help_text="Total storage in TB")),
            ],
        ),
    ]
